export interface SentenceItem {
  id: number;
  keyword: string;
  sentence: string; // The grammatically correct sentence
  rawSentence: string; // Original user input
  grammarFixed: boolean;
  grammarNote?: string;
  urduTranslation: string;
  urduKeyword: string;
  emoji: string;
  badgeColor: string;
  gradient: string;
  bgLight: string;
  category: string;
  hint: string;
}

export const SENTENCE_LIST: SentenceItem[] = [
  {
    id: 1,
    keyword: 'pretty',
    sentence: 'My mom is pretty.',
    rawSentence: 'My mom is pretty.',
    grammarFixed: false,
    urduTranslation: 'میری امی پیاری / خوبصورت ہیں۔',
    urduKeyword: 'خوبصورت / پیاری',
    emoji: '🌸',
    badgeColor: 'bg-pink-100 text-pink-700 border-pink-300',
    gradient: 'from-pink-500 to-rose-400',
    bgLight: 'bg-pink-50/70 border-pink-200',
    category: 'Family & Feelings',
    hint: 'Beautiful and pleasant to look at',
  },
  {
    id: 2,
    keyword: 'garden',
    sentence: 'I play in the garden.',
    rawSentence: 'I play in the garden.',
    grammarFixed: false,
    urduTranslation: 'میں باغ میں کھیلتا ہوں۔',
    urduKeyword: 'باغ',
    emoji: '🌳',
    badgeColor: 'bg-emerald-100 text-emerald-700 border-emerald-300',
    gradient: 'from-emerald-500 to-teal-400',
    bgLight: 'bg-emerald-50/70 border-emerald-200',
    category: 'Places & Play',
    hint: 'A green open space with plants and flowers',
  },
  {
    id: 3,
    keyword: 'healthy',
    sentence: 'I eat healthy food.',
    rawSentence: 'I eat healthy food.',
    grammarFixed: false,
    urduTranslation: 'میں صحت بخش کھانا کھاتا ہوں۔',
    urduKeyword: 'صحت بخش',
    emoji: '🥗',
    badgeColor: 'bg-lime-100 text-lime-700 border-lime-300',
    gradient: 'from-lime-500 to-green-500',
    bgLight: 'bg-lime-50/70 border-lime-200',
    category: 'Health & Food',
    hint: 'Food that makes your body strong and active',
  },
  {
    id: 4,
    keyword: 'nest',
    sentence: 'The bird is in the nest.',
    rawSentence: 'Bird is in the nest.',
    grammarFixed: true,
    grammarNote: "In English, singular countable nouns take an article: 'The bird is in the nest.'",
    urduTranslation: 'پرندہ گھونسلے میں ہے۔',
    urduKeyword: 'گھونسلا',
    emoji: '🪺',
    badgeColor: 'bg-amber-100 text-amber-700 border-amber-300',
    gradient: 'from-amber-500 to-yellow-400',
    bgLight: 'bg-amber-50/70 border-amber-200',
    category: 'Nature & Birds',
    hint: 'A cozy home made by birds for their eggs and chicks',
  },
  {
    id: 5,
    keyword: 'fish',
    sentence: 'I like to eat fish.',
    rawSentence: 'I like to eat fish.',
    grammarFixed: false,
    urduTranslation: 'مجھے مچھلی کھانا پسند ہے۔',
    urduKeyword: 'مچھلی',
    emoji: '🐟',
    badgeColor: 'bg-cyan-100 text-cyan-700 border-cyan-300',
    gradient: 'from-cyan-500 to-blue-400',
    bgLight: 'bg-cyan-50/70 border-cyan-200',
    category: 'Food & Animals',
    hint: 'A water animal that swims with fins',
  },
  {
    id: 6,
    keyword: 'basket',
    sentence: 'The fruits are in the basket.',
    rawSentence: 'Fruits are in the basket.',
    grammarFixed: true,
    grammarNote: "Added 'The' to specify the fruits inside the basket.",
    urduTranslation: 'پھل ٹوکری میں ہیں۔',
    urduKeyword: 'ٹوکری',
    emoji: '🧺',
    badgeColor: 'bg-orange-100 text-orange-700 border-orange-300',
    gradient: 'from-orange-500 to-amber-500',
    bgLight: 'bg-orange-50/70 border-orange-200',
    category: 'Objects & Food',
    hint: 'A woven container used to hold fruits and goodies',
  },
  {
    id: 7,
    keyword: 'sleeping',
    sentence: 'The cat is sleeping on the mat.',
    rawSentence: 'Cat is sleeping on the mat.',
    grammarFixed: true,
    grammarNote: "Singular noun 'cat' needs 'The': 'The cat is sleeping on the mat.'",
    urduTranslation: 'بلی چٹائی پر سو رہی ہے۔',
    urduKeyword: 'سو رہی ہے',
    emoji: '🐱',
    badgeColor: 'bg-purple-100 text-purple-700 border-purple-300',
    gradient: 'from-purple-500 to-indigo-400',
    bgLight: 'bg-purple-50/70 border-purple-200',
    category: 'Animals & Actions',
    hint: 'Resting peacefully with eyes closed',
  },
  {
    id: 8,
    keyword: 'market',
    sentence: 'This is a fish market.',
    rawSentence: 'This is a fish market.',
    grammarFixed: false,
    urduTranslation: 'یہ مچھلی کی مارکیٹ / منڈی ہے۔',
    urduKeyword: 'مارکیٹ / منڈی',
    emoji: '🏪',
    badgeColor: 'bg-teal-100 text-teal-700 border-teal-300',
    gradient: 'from-teal-500 to-emerald-400',
    bgLight: 'bg-teal-50/70 border-teal-200',
    category: 'Places',
    hint: 'A bustling place where fresh fish is sold',
  },
  {
    id: 9,
    keyword: 'drum',
    sentence: 'I have a drum.',
    rawSentence: 'I have a drum.',
    grammarFixed: false,
    urduTranslation: 'میرے پاس ایک ڈھول ہے۔',
    urduKeyword: 'ڈھول',
    emoji: '🥁',
    badgeColor: 'bg-red-100 text-red-700 border-red-300',
    gradient: 'from-red-500 to-rose-400',
    bgLight: 'bg-red-50/70 border-red-200',
    category: 'Music & Toys',
    hint: 'A musical instrument you tap to make beats',
  },
  {
    id: 10,
    keyword: 'clock',
    sentence: 'The clock shows us time.',
    rawSentence: 'Clock shows us time.',
    grammarFixed: true,
    grammarNote: "Singular noun 'clock' takes 'The' or 'A': 'The clock shows us time.'",
    urduTranslation: 'گھڑی ہمیں وقت بتاتی ہے۔',
    urduKeyword: 'گھڑی',
    emoji: '⏰',
    badgeColor: 'bg-sky-100 text-sky-700 border-sky-300',
    gradient: 'from-sky-500 to-blue-500',
    bgLight: 'bg-sky-50/70 border-sky-200',
    category: 'Time & Objects',
    hint: 'A round device that ticks and tells the time',
  },
  {
    id: 11,
    keyword: 'jump',
    sentence: 'I can jump.',
    rawSentence: 'I can jump.',
    grammarFixed: false,
    urduTranslation: 'میں چھلانگ لگا سکتا ہوں۔',
    urduKeyword: 'چھلانگ لگانا',
    emoji: '🦘',
    badgeColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    gradient: 'from-yellow-500 to-amber-500',
    bgLight: 'bg-yellow-50/70 border-yellow-200',
    category: 'Actions & Fun',
    hint: 'Bouncing high into the air with joy',
  },
  {
    id: 12,
    keyword: 'house',
    sentence: 'My house is clean.',
    rawSentence: 'My house is clean.',
    grammarFixed: false,
    urduTranslation: 'میرا گھر صاف ستھرا ہے۔',
    urduKeyword: 'گھر',
    emoji: '🏠',
    badgeColor: 'bg-blue-100 text-blue-700 border-blue-300',
    gradient: 'from-blue-500 to-indigo-500',
    bgLight: 'bg-blue-50/70 border-blue-200',
    category: 'Home & Living',
    hint: 'A warm and clean home where family stays together',
  },
  {
    id: 13,
    keyword: 'hot',
    sentence: 'The tea is hot.',
    rawSentence: 'Tea is hot.',
    grammarFixed: true,
    grammarNote: "In conversational English, 'The tea is hot.' is standard when referring to the tea in cup.",
    urduTranslation: 'چائے گرم ہے۔',
    urduKeyword: 'گرم',
    emoji: '☕',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    gradient: 'from-orange-500 to-red-500',
    bgLight: 'bg-amber-50/70 border-amber-200',
    category: 'Drinks & Feelings',
    hint: 'Steaming warm drink that needs careful sipping',
  },
  {
    id: 14,
    keyword: 'bag',
    sentence: 'My bag is new.',
    rawSentence: 'My bag is new.',
    grammarFixed: false,
    urduTranslation: 'میرا بستہ نیا ہے۔',
    urduKeyword: 'بستہ / بیگ',
    emoji: '🎒',
    badgeColor: 'bg-violet-100 text-violet-700 border-violet-300',
    gradient: 'from-violet-500 to-purple-500',
    bgLight: 'bg-violet-50/70 border-violet-200',
    category: 'School & Things',
    hint: 'A shiny new school bag for notebooks and pencils',
  },
  {
    id: 15,
    keyword: 'crying',
    sentence: 'The baby is crying.',
    rawSentence: 'Baby is crying.',
    grammarFixed: true,
    grammarNote: "Singular noun 'baby' needs an article: 'The baby is crying.'",
    urduTranslation: 'بچہ رو رہا ہے۔',
    urduKeyword: 'رو رہا ہے',
    emoji: '👶',
    badgeColor: 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-300',
    gradient: 'from-fuchsia-500 to-pink-500',
    bgLight: 'bg-fuchsia-50/70 border-fuchsia-200',
    category: 'Feelings & People',
    hint: 'The little baby is crying for milk or sleep',
  },
];
