import type { Metadata } from "next";
import "./globals.css";
import AppShell from "./components/AppShell";



export const metadata: Metadata = {
  title: "MasterSahib",
  description: "Generated by create next app",
  icons: {
    icon: '/images/main_logo.png',
    shortcut: '/images/main_logo.png',
    apple: '/images/main_logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className="min-h-screen bg-gradient-to-b from-indigo-50 to-white"
          >
       <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
