export type EducationalResourceItem = {
  title: string;
  description: string;
  status: 'Ready' | 'Coming Soon';
  href?: string;
  showInNavbar?: boolean;
  addedOn?: string;
  ageGroup?: '3-6' | '5-11' | '7-12' | '13-16' | 'general' | 'parents';
  category?: 'kids' | 'teachers' | 'parents';
  icon?: string;
  color?: string;
};

export const educationalResourceItems: EducationalResourceItem[] = [
  {
    title: 'Students Age Calculator',
    description: 'Calculate exact student age and view a recommended class instantly.',
    status: 'Ready',
    href: '/educational-resources/students-age-calculator',
    addedOn: '2025-12-15',
    ageGroup: 'general',
    category: 'teachers',
    icon: '📅',
    color: 'from-blue-500 to-cyan-400',
  },
  {
    title: 'Lesson Plan',
    description: 'Generate a complete lesson plan from a topic, PDF, or image.',
    status: 'Ready',
    href: '/educational-resources/automatic-lesson-plan',
    addedOn: '2026-01-10',
    ageGroup: 'general',
    category: 'teachers',
    icon: '📝',
    color: 'from-indigo-500 to-purple-400',
  },
  {
    title: 'Academic Calendar Generator',
    description: 'Generate a yearly school calendar with holidays, vacation periods, and working-day totals.',
    status: 'Ready',
    href: '/educational-resources/academic-calendar',
    addedOn: '2026-02-12',
    ageGroup: 'general',
    category: 'teachers',
    icon: '🗓️',
    color: 'from-violet-500 to-pink-400',
  },
  {
    title: 'Timetable Generator',
    description: 'Create a balanced weekly school timetable with manual swap, PDF, and print support.',
    status: 'Ready',
    href: '/educational-resources/timetable-generator',
    addedOn: '2026-03-18',
    ageGroup: 'general',
    category: 'teachers',
    icon: '⏰',
    color: 'from-emerald-500 to-teal-400',
  },
  {
    title: 'O Level Career Selection Helper',
    description: 'Answer 20 smart questions and get subject combinations based on your career goals in Pakistan.',
    status: 'Ready',
    href: '/educational-resources/o-level-career-selection',
    addedOn: '2026-04-20',
    ageGroup: '13-16',
    category: 'kids',
    icon: '🎯',
    color: 'from-amber-500 to-orange-400',
  },
  {
    title: 'Resume Builder',
    description: 'Create a teacher CV or resume quickly for applications and updates.',
    status: 'Ready',
    href: '/resume-builder',
    addedOn: '2026-02-01',
    ageGroup: 'general',
    category: 'teachers',
    icon: '📄',
    color: 'from-slate-600 to-slate-400',
  },
  {
    title: 'Attendance Tracker',
    description: 'Simple attendance workflow for class-wise management.',
    status: 'Ready',
    href: '/educational-resources/attendance-tracker',
    showInNavbar: false,
    addedOn: '2025-11-20',
    ageGroup: 'general',
    category: 'teachers',
    icon: '📋',
    color: 'from-sky-500 to-blue-400',
  },
  {
    title: 'Worksheet Builder',
    description: 'Create print-ready worksheets from website topics or generate custom AI worksheets.',
    status: 'Ready',
    href: '/educational-resources/worksheet-builder',
    addedOn: '2025-11-01',
    ageGroup: 'general',
    category: 'teachers',
    icon: '📝',
    color: 'from-amber-500 to-orange-400',
  },
  {
    title: 'Class Routine Board',
    description: 'Keep your daily timetable and classroom flow in one place.',
    status: 'Coming Soon',
    showInNavbar: false,
    addedOn: '2025-10-15',
    ageGroup: 'general',
    category: 'teachers',
    icon: '🪧',
    color: 'from-gray-400 to-gray-300',
  },
  {
    title: 'Daily Exit Ticket',
    description: 'Students write one thing they learned before leaving class. Builds reflection habit.',
    status: 'Ready',
    href: '/educational-resources/exit-ticket',
    addedOn: '2026-06-23',
    ageGroup: '7-12',
    category: 'teachers',
    icon: '🎟️',
    color: 'from-rose-500 to-pink-400',
  },
  {
    title: 'Typing Practice Tutor',
    description: 'Improve typing speed & accuracy across multiple levels with streaks, WPM tracking, and history.',
    status: 'Ready',
    href: '/educational-resources/typing-tutor',
    addedOn: '2026-06-23',
    ageGroup: '7-12',
    category: 'kids',
    icon: '⌨️',
    color: 'from-cyan-500 to-blue-400',
  },
  {
    title: 'Art Gallery Wall',
    description: 'Showcase student drawings and creative work in a beautiful gallery wall with likes.',
    status: 'Ready',
    href: '/educational-resources/art-gallery',
    addedOn: '2026-06-23',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🎨',
    color: 'from-pink-500 to-rose-400',
  },
  {
    title: 'Weekly Assembly Plan Maker',
    description: 'Create A4-printable assembly plans with topics, speakers, duties, and customizable school details.',
    status: 'Ready',
    href: '/educational-resources/assembly-planner',
    addedOn: '2026-06-23',
    ageGroup: 'general',
    category: 'teachers',
    icon: '🎤',
    color: 'from-fuchsia-500 to-purple-400',
  },
  {
    title: 'ABC Alphabet Learning',
    description: 'Interactive alphabet tracing and phonics for early learners. Fun animations and sounds.',
    status: 'Ready',
    href: '/educational-resources/alphabet-learning',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🔤',
    color: 'from-red-500 to-orange-400',
  },
  {
    title: 'Number Fun (1-100)',
    description: 'Learn numbers 1 to 100 with colorful counting games and simple math activities.',
    status: 'Ready',
    href: '/educational-resources/number-fun',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🔢',
    color: 'from-blue-500 to-indigo-400',
  },
  {
    title: 'Science Experiments (Ages 7-12)',
    description: 'Simple hands-on science experiments using household items. Learn while doing.',
    status: 'Ready',
    href: '/educational-resources/science-experiments',
    addedOn: '2026-06-24',
    ageGroup: '7-12',
    category: 'kids',
    icon: '🔬',
    color: 'from-teal-500 to-emerald-400',
  },
  {
    title: 'Creative Writing Prompts',
    description: 'Fun story starters and writing challenges for young writers to explore their imagination.',
    status: 'Ready',
    href: '/educational-resources/creative-writing',
    addedOn: '2026-06-24',
    ageGroup: '7-12',
    category: 'kids',
    icon: '✍️',
    color: 'from-violet-500 to-indigo-400',
  },
  {
    title: 'English Grammar Basics',
    description: 'Parts of speech, tenses, and sentence structure explained simply with examples.',
    status: 'Ready',
    href: '/educational-resources/english-grammar',
    addedOn: '2026-06-24',
    ageGroup: '13-16',
    category: 'kids',
    icon: '📖',
    color: 'from-emerald-500 to-green-400',
  },
  {
    title: 'Mathematics Practice (Secondary)',
    description: 'Algebra, geometry, and trigonometry practice sets with step-by-step solutions.',
    status: 'Ready',
    href: '/educational-resources/math-secondary',
    addedOn: '2026-06-24',
    ageGroup: '13-16',
    category: 'kids',
    icon: '📐',
    color: 'from-orange-500 to-amber-400',
  },
  {
    title: 'Urdu Reading for Kids',
    description: 'Simple Urdu stories and poems for early readers with audio pronunciation guide.',
    status: 'Ready',
    href: '/educational-resources/urdu-reading',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '📗',
    color: 'from-green-500 to-lime-400',
  },
  {
    title: 'Shape Learning Fun',
    description: 'Learn shapes like circle, heart, star, triangle, cone, oval, rectangle, square with colors and sounds. Ages 3-4.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=shapes',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '⭐',
    color: 'from-yellow-500 to-amber-400',
  },
  {
    title: 'Spelling Bee Fun',
    description: 'Listen to the word, type the spelling. Includes vocal pronunciation for early learners.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=spell',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🐝',
    color: 'from-yellow-500 to-orange-400',
  },
  {
    title: 'Fill in the Blanks',
    description: 'Complete sentences by filling missing words. Fun way to learn vocabulary and grammar.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=blanks',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '📝',
    color: 'from-blue-500 to-purple-400',
  },
  {
    title: '3D Shapes Learning',
    description: 'Learn 3D shapes like cube, sphere, cone, pyramid and more with sounds, quiz, and auto-learn modes.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=d3',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🧊',
    color: 'from-cyan-500 to-blue-400',
  },
  {
    title: 'Colors Learning',
    description: 'Learn colors with fun visuals and a quiz game. Hear each color name pronounced aloud.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=colors',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🌈',
    color: 'from-pink-500 via-red-500 via-amber-500 via-green-500 to-blue-500',
  },
  {
    title: 'Sight Words Spelling',
    description: 'Practice spelling common sight words like Cat, Dog, Sun, Hat with letter tiles and hints.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=sight',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '👁️',
    color: 'from-purple-500 to-pink-400',
  },
  {
    title: 'Teen Words (13-19)',
    description: 'Learn number words thirteen to nineteen with quiz, fill-the-name, and auto-learn memorization.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=teen',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🔟',
    color: 'from-indigo-500 to-violet-400',
  },
  {
    title: 'Ty Words (20-90)',
    description: 'Learn tens number words twenty to ninety with quiz, fill-the-name, and auto-learn memorization.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=ty',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '💯',
    color: 'from-fuchsia-500 to-purple-400',
  },
  {
    title: 'Days of the Week',
    description: 'Learn the seven days: Monday to Sunday with fun games, auto-learn, and fill-the-name activities.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=days',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '📅',
    color: 'from-sky-500 to-indigo-400',
  },
  {
    title: 'Vegetables Names',
    description: 'Learn vegetable names like Potato, Tomato, Carrot and more with pictures, sounds, and quizzes.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=veg',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🥕',
    color: 'from-orange-500 to-green-500',
  },
  {
    title: 'Garden Objects',
    description: 'Explore garden items like flowers, trees, butterflies, and swings with interactive learning.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=garden',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🌻',
    color: 'from-green-500 to-yellow-500',
  },
  {
    title: 'Kitchen Objects',
    description: 'Learn kitchen items like stove, plate, spoon, and kettle with fun visuals and voice.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=kitchen',
    addedOn: '2026-06-24',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🍳',
    color: 'from-red-500 to-amber-400',
  },
  {
    title: 'Occupations',
    description: 'Learn about doctors, teachers, pilots, and more with fun visuals, sounds, and quizzes.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=occupation',
    addedOn: '2026-07-02',
    ageGroup: '3-6',
    category: 'kids',
    icon: '👨‍⚕️',
    color: 'from-blue-500 to-teal-400',
  },
  {
    title: 'Birds Names',
    description: 'Learn bird names like parrot, peacock, eagle, and more with sounds and picture games.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=birds',
    addedOn: '2026-07-02',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🦜',
    color: 'from-green-500 to-emerald-400',
  },
  {
    title: 'Animals Names',
    description: 'Learn animal names like lion, elephant, giraffe, and more with fun visuals and quizzes.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=animals',
    addedOn: '2026-07-02',
    ageGroup: '3-6',
    category: 'kids',
    icon: '🦁',
    color: 'from-amber-500 to-orange-400',
  },
  {
    title: 'Months of the Year',
    description: 'Learn the twelve months from January to December with auto-learn, quiz, and fill-the-name.',
    status: 'Ready',
    href: '/educational-resources/fun-learning?tab=months',
    addedOn: '2026-07-02',
    ageGroup: '3-6',
    category: 'kids',
    icon: '📆',
    color: 'from-teal-500 to-cyan-400',
  },
  {
    title: 'Math Practice (Ages 5-11)',
    description: 'Addition, subtraction, multiplication, division — age-wise levels with sub-topics, difficulty modes, hints, and progress tracking.',
    status: 'Ready',
    href: '/educational-resources/math-practice',
    addedOn: '2026-06-24',
    ageGroup: '5-11',
    category: 'kids',
    icon: '🧮',
    color: 'from-rose-500 to-pink-400',
  },
  {
    title: 'Table Times Learning',
    description: 'Learn multiplication tables from 2 to 20 with interactive practice, sound, and quizzes.',
    status: 'Ready',
    href: '/educational-resources/table-times',
    addedOn: '2026-07-03',
    ageGroup: '5-11',
    category: 'kids',
    icon: '✖️',
    color: 'from-purple-500 to-indigo-400',
  },
  {
    title: 'Parent Dashboard',
    description: 'Track your child\'s progress across all learning activities and see daily reports.',
    status: 'Coming Soon',
    addedOn: '2026-06-24',
    ageGroup: 'parents',
    category: 'parents',
    icon: '📊',
    color: 'from-slate-500 to-gray-400',
  },
  {
    title: 'Activity Suggestions (Ages 3-6)',
    description: 'Fun home activities for parents to do with their young children. No screens needed.',
    status: 'Coming Soon',
    addedOn: '2026-06-24',
    ageGroup: 'parents',
    category: 'parents',
    icon: '🏠',
    color: 'from-slate-500 to-gray-400',
  },
  {
    title: 'Progress Report Generator',
    description: 'Generate a personalized progress report for your child across all subjects.',
    status: 'Coming Soon',
    addedOn: '2026-06-24',
    ageGroup: 'parents',
    category: 'parents',
    icon: '📈',
    color: 'from-slate-500 to-gray-400',
  },
];

const getAddedTimestamp = (item: EducationalResourceItem, index: number) => {
  if (item.addedOn) {
    const parsed = Date.parse(item.addedOn);
    if (!Number.isNaN(parsed)) {
      return parsed;
    }
  }
  return index;
};

export const sortedEducationalResourceItems = educationalResourceItems
  .map((item, index) => ({ item, index }))
  .sort((a, b) => getAddedTimestamp(b.item, b.index) - getAddedTimestamp(a.item, a.index))
  .map(({ item }) => item);

export const latestEducationalResourceTitles = sortedEducationalResourceItems
  .filter((item) => item.status === 'Ready' && item.href && item.href !== '#')
  .slice(0, 2)
  .map((item) => item.title);

export const educationalResourceNavLinks = sortedEducationalResourceItems
  .filter((item) => item.status === 'Ready' && item.href && item.href !== '#' && item.showInNavbar !== false)
  .map((item) => ({
    label: item.title,
    href: item.href as string,
    description: item.description,
  }));
